import * as THREE from 'three';
import {createCity} from './city.js';
import {OrbitControls} from './OrbitControls.js';
import {example,area,head,total,step,balance,rebase,TYPES,validateNode} from './sim.js';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const fmt=(v,d=2)=>Number(v).toLocaleString('en-US',{minimumFractionDigits:d,maximumFractionDigits:d});
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state=example(),snapshot=structuredClone(state),selected={kind:'node',id:'n3'},mode='select',connectionStart=null,running=false,speed=5,nextId=10,toastTimer,accumulator=0;
const viewport=$('#viewport'),host=$('#canvas-host');let renderer;
try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:false});}catch(err){$('#webgl-error').hidden=false;throw err;}
renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.setClearColor(0xeaf0f0);renderer.outputColorSpace=THREE.SRGBColorSpace;host.appendChild(renderer.domElement);
const scene=new THREE.Scene();scene.fog=new THREE.Fog(0xeaf0f0,420,850);
const camera=new THREE.PerspectiveCamera(38,1,.1,1400);camera.position.set(185,205,235);
const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,0,0);controls.enableDamping=true;controls.dampingFactor=.09;controls.maxPolarAngle=Math.PI/2.07;controls.minDistance=60;controls.maxDistance=950;controls.mouseButtons={LEFT:null,MIDDLE:THREE.MOUSE.PAN,RIGHT:THREE.MOUSE.ROTATE};controls.touches={ONE:THREE.TOUCH.PAN,TWO:THREE.TOUCH.DOLLY_PAN};
scene.add(new THREE.HemisphereLight(0xffffff,0x718d81,2.1));const sun=new THREE.DirectionalLight(0xfff8e8,2.5);sun.position.set(-80,150,75);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-160,right:160,top:160,bottom:-160,near:1,far:400});sun.shadow.normalBias=.08;scene.add(sun);
const mat=(color,opts={})=>new THREE.MeshStandardMaterial({color,roughness:.88,...opts});
const landMat=mat(0xa5b99a),wallMat=mat(0xa5aaa0),floorMat=mat(0x6b827b),pipeMat=mat(0x91aeb3,{metalness:.28,roughness:.45}),gateMat=mat(0xed9e58,{metalness:.16,roughness:.5}),darkMat=mat(0x395d64,{metalness:.3}),waterMat=mat(0x318b9a,{transparent:true,opacity:.84,roughness:.28,metalness:.1,side:THREE.DoubleSide});
const clockUniform={value:0};waterMat.onBeforeCompile=shader=>{shader.uniforms.time=clockUniform;shader.vertexShader='varying vec3 waterPos;\n'+shader.vertexShader.replace('#include <begin_vertex>','#include <begin_vertex>\nwaterPos=position;');shader.fragmentShader='uniform float time;varying vec3 waterPos;\n'+shader.fragmentShader.replace('#include <color_fragment>','#include <color_fragment>\nfloat r=sin(waterPos.x*1.8+waterPos.z*.7+time)*sin(waterPos.z*1.3-time*.4);diffuseColor.rgb+=r*.012;');};
function box(w,h,d,material,x=0,y=0,z=0){const m=new THREE.Mesh(new THREE.BoxGeometry(w,Math.max(.025,h),d),material);m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;return m;}
let city=null,showCity=true,showGrid=false,showLabels=true;
const world=new THREE.Group();scene.add(world);let pickables=[],nodeMeshes=new Map(),edgeMeshes=new Map(),labelElements=new Map();const raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2();const plane=new THREE.Plane(new THREE.Vector3(0,1,0),0);
const sharedMaterials=new Set([landMat,wallMat,floorMat,pipeMat,gateMat,darkMat,waterMat]);
function disposeGroup(group){group.traverse(o=>{if(o.geometry)o.geometry.dispose();if(o.material&&!sharedMaterials.has(o.material))o.material.dispose();});group.clear();}
function tag(group,kind,id){group.traverse(o=>{if(o.isMesh){o.userData={kind,id};pickables.push(o);}});}
function findNode(id){return state.nodes.find(n=>n.id===id);}function findEdge(id){return state.edges.find(e=>e.id===id);}
function openingLimit(e){if(e.type==='pipe')return e.width;if(!e.dam)return 4;const a=findNode(e.a),b=findNode(e.b),base=Math.max(a.bed,b.bed);return Math.max(.2,Math.min(4,(e.crest??base+3)-base));}
function endPoint(n,other){const dx=other.x-n.x,dz=other.z-n.z;const t=Math.min(n.width/2/Math.max(.001,Math.abs(dx)),n.length/2/Math.max(.001,Math.abs(dz)));return new THREE.Vector3(n.x+dx*t,n.bed,n.z+dz*t);}
function beamBetween(a,b,width,height,material,group){const len=a.distanceTo(b);const m=box(width,height,len,material);m.position.copy(a).add(b).multiplyScalar(.5);m.quaternion.setFromUnitVectors(new THREE.Vector3(0,0,1),b.clone().sub(a).normalize());group.add(m);return m;}
function rebuild({refreshCity=true}={}){
 if(refreshCity){if(city)city.dispose();city=createCity(state);scene.add(city.root);city.urban.visible=showCity;city.grid.visible=showGrid;}
 disposeGroup(world);pickables=[];nodeMeshes.clear();edgeMeshes.clear();$('#labels').replaceChildren();labelElements.clear();
 for(const n of state.nodes){
  const g=new THREE.Group();g.position.set(n.x,0,n.z);const w=n.width,l=n.length,b=n.bed,h=n.bank;
  // The carved terrain itself forms the sloping bank and basin floor.

  // The water surface and walls share the same meter scale on every axis.
  const cuts={left:[],right:[],front:[],back:[]};
  for(const edge of state.edges.filter(e=>e.a===n.id||e.b===n.id)){
   const other=findNode(edge.a===n.id?edge.b:edge.a);if(!other)continue;
   const ep=endPoint(n,other),dx=other.x-n.x,dz=other.z-n.z,dist=Math.hypot(dx,dz);
   if(Math.abs(Math.abs(ep.x-n.x)-w/2)<.01){const half=(edge.width+1)/2/Math.max(.2,Math.abs(dx)/dist);cuts[dx>0?'right':'left'].push([ep.z-n.z-half,ep.z-n.z+half]);}
   else {const half=(edge.width+1)/2/Math.max(.2,Math.abs(dz)/dist);cuts[dz>0?'back':'front'].push([ep.x-n.x-half,ep.x-n.x+half]);}
  }
  for(const side of ['left','right','front','back']){
   const alongZ=side==='left'||side==='right',half=alongZ?l/2:w/2;let cursor=-half;
   const intervals=cuts[side].sort((a,b)=>a[0]-b[0]);
   const wall=()=>{};;
   for(const [lo,hi] of intervals){wall(cursor,Math.min(half,lo));cursor=Math.max(cursor,Math.min(half,hi));}wall(cursor,half);
  }
  const water=box(w,1,l,waterMat,0,b+.5,0);water.castShadow=false;g.add(water);
  const outline=new THREE.LineSegments(new THREE.EdgesGeometry(new THREE.BoxGeometry(w+3,.12,l+3)),new THREE.LineBasicMaterial({color:0x087e79,linewidth:2}));outline.position.y=b+h+.12;outline.visible=selected?.id===n.id;g.add(outline);
  const overflow=box(w+2,.15,l+2,mat(0xe2854c,{transparent:true,opacity:.45}),0,b+h+.1,0);overflow.visible=false;g.add(overflow);
  if(n.source||n.sink){const marker=box(2,5,2,n.source?mat(0x258378):darkMat,-w/2-3,b+2.5,-l/2);g.add(marker);}
  world.add(g);tag(g,'node',n.id);nodeMeshes.set(n.id,{g,water,outline,overflow});
  const label=document.createElement('div');label.className='node-label';label.dataset.node=n.id;$('#labels').append(label);labelElements.set(n.id,label);
 }
 for(const e of state.edges){
  const a=findNode(e.a),b=findNode(e.b);if(!a||!b)continue;
  const p=endPoint(a,b),q=endPoint(b,a);const g=new THREE.Group();const center=p.clone().add(q).multiplyScalar(.5);const dir=q.clone().sub(p).setY(0).normalize();const perp=new THREE.Vector3(-dir.z,0,dir.x);const length=Math.max(1,Math.hypot(q.x-p.x,q.z-p.z));let water;
  if(e.type==='pipe'){
   const diameter=e.width;const pa=p.clone(),pb=q.clone();pa.y=a.bed+diameter/2;pb.y=b.bed+diameter/2;
   const tube=new THREE.Mesh(new THREE.CylinderGeometry(diameter/2,diameter/2,pa.distanceTo(pb),12),pipeMat);tube.position.copy(pa).add(pb).multiplyScalar(.5);tube.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),pb.clone().sub(pa).normalize());tube.castShadow=true;g.add(tube);
   for(const t of [.1,.5,.9]){const joint=new THREE.Mesh(new THREE.CylinderGeometry(diameter*.62,diameter*.62,.6,12),darkMat);joint.position.copy(pa).lerp(pb,t);joint.quaternion.copy(tube.quaternion);g.add(joint);}
  }else{
   beamBetween(p.clone().add(new THREE.Vector3(0,-.12,0)),q.clone().add(new THREE.Vector3(0,-.12,0)),e.width+.8,.3,floorMat,g);
   for(const sign of [-1,1]){const p1=p.clone().addScaledVector(perp,sign*(e.width/2+.3)),q1=q.clone().addScaledVector(perp,sign*(e.width/2+.3));const bankHeight=Math.max(a.bank,b.bank);p1.y+=bankHeight/2;q1.y+=bankHeight/2;beamBetween(p1,q1,.6,bankHeight,wallMat,g);}
   const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(new Float32Array(12),3));geo.setIndex([0,1,2,2,1,3]);geo.computeVertexNormals();water=new THREE.Mesh(geo,waterMat);g.add(water);
  }
  const dots=[];for(let i=0;i<4;i++){const dot=new THREE.Mesh(new THREE.ConeGeometry(e.type==='pipe'?.5:.85,2.1,3),new THREE.MeshBasicMaterial({color:0xe5ffff,transparent:true,opacity:.85}));dot.rotation.x=Math.PI/2;g.add(dot);dots.push(dot);}
  let gate;
  if(e.gate&&!e.dam){const base=Math.max(a.bed,b.bed);gate=new THREE.Group();gate.position.set(center.x,base,center.z);gate.rotation.y=Math.atan2(dir.x,dir.z);const w=e.type==='pipe'?Math.max(2,e.width):e.width;
   gate.add(box(.65,5,.8,darkMat,-w/2-.7,2.5,0));gate.add(box(.65,5,.8,darkMat,w/2+.7,2.5,0));gate.add(box(w+2,.55,.9,gateMat,0,5,0));
   const blade=box(w,2.5,.35,gateMat,0,e.opening+1.25,0);gate.add(blade);const stem=box(.18,2,.18,darkMat,0,5.5,0);gate.add(stem);g.add(gate);gate.userData.blade=blade;
  }
  // A generous invisible hit area makes small connectors usable with touch.
  const pick=beamBetween(p.clone().add(new THREE.Vector3(0,1,0)),q.clone().add(new THREE.Vector3(0,1,0)),Math.max(3,e.width),3,new THREE.MeshBasicMaterial({transparent:true,opacity:0,depthWrite:false}),g);
  world.add(g);if(e.dam&&e.type==='channel'){const base=Math.max(a.bed,b.bed),crest=e.crest??base+3,damHeight=Math.max(.5,crest-base),span=e.width+2.7,gateWidth=Math.min(1.65,e.width*.31),pier=.35,rotation=Math.atan2(dir.x,dir.z);const wall=new THREE.Group();wall.position.copy(center);wall.rotation.y=rotation;const wing=(span-2*gateWidth-3*pier)/2;let cursor=-span/2;for(const segment of [wing,pier,gateWidth,pier,gateWidth,pier,wing]){if(segment>.08){const x=cursor+segment/2;wall.add(box(segment,damHeight,2.2,mat(0xb7bdb7,{roughness:.84}),x,damHeight/2,0));if(Math.abs(x)>span*.36){wall.add(box(segment+.45,.36,3,mat(0x858f90),x,damHeight-.12,0));}}cursor+=segment;}const blades=[];if(e.gate)for(const x of [-gateWidth/2-pier/2,gateWidth/2+pier/2]){const blade=box(gateWidth,Math.max(.12,damHeight-e.opening),.42,gateMat,x,e.opening+(damHeight-e.opening)/2,0);wall.add(blade);blades.push(blade);const stem=box(.12,damHeight+1,.13,darkMat,x,damHeight/2+.3,0);wall.add(stem);const cap=box(gateWidth+.7,.24,.7,darkMat,x,damHeight-.16,0);wall.add(cap);}g.add(wall);gate={userData:{blades,damHeight},group:wall};}
  tag(g,'edge',e.id);edgeMeshes.set(e.id,{g,water,p,q,perp,dots,gate,center,pick,length});
 }
 $('#object-count').textContent=`${state.nodes.length} แหล่งน้ำ · ${city.stats.buildings} อาคาร · ${city.stats.bridges} สะพาน · ${state.edges.filter(e=>e.dam).length} เขื่อน`;
 updateVisuals(0);renderInspector();
}
function updateVisuals(t){
 camera.updateMatrixWorld(true);
 for(const n of state.nodes){const o=nodeMeshes.get(n.id);if(!o)continue;const depth=n.volume/area(n);o.water.scale.y=Math.max(.01,depth);o.water.position.y=n.bed+depth/2;o.water.visible=depth>.003;o.outline.visible=selected?.kind==='node'&&selected.id===n.id;o.overflow.visible=n.spill>0;
  const el=labelElements.get(n.id);const pt=new THREE.Vector3(n.x,n.bed+n.bank+2,n.z).project(camera);el.style.left=`${(pt.x*.5+.5)*host.clientWidth}px`;el.style.top=`${(-pt.y*.5+.5)*host.clientHeight}px`;el.style.display=!showLabels||pt.z>1||(host.clientWidth<500&&n.id!==selected?.id&&!n.source&&!n.sink)?'none':'block';el.className='node-label'+(selected?.id===n.id?' selected':'')+(n.spill>0?' spill':'');el.innerHTML=`${esc(n.name)}${n.source?' · น้ำเข้า':n.sink?' · น้ำออก':''}<b>${fmt(head(n))} ม.</b>`;
 }
 for(const e of state.edges){const o=edgeMeshes.get(e.id),a=findNode(e.a),b=findNode(e.b);if(!o)continue;
  if(o.water){const data=o.water.geometry.attributes.position;const pts=[o.p.clone().addScaledVector(o.perp,-e.width/2),o.p.clone().addScaledVector(o.perp,e.width/2),o.q.clone().addScaledVector(o.perp,-e.width/2),o.q.clone().addScaledVector(o.perp,e.width/2)];pts[0].y=pts[1].y=head(a);pts[2].y=pts[3].y=head(b);pts.forEach((v,i)=>data.setXYZ(i,v.x,v.y+.04,v.z));data.needsUpdate=true;o.water.geometry.computeVertexNormals();o.water.visible=a.volume+b.volume>1;}
  if(o.gate?.userData?.blade)o.gate.userData.blade.position.y=e.opening+1.25;if(o.gate?.userData?.blades)o.gate.userData.blades.forEach(blade=>{const h=Math.max(.12,o.gate.userData.damHeight-e.opening);blade.geometry.dispose();blade.geometry=new THREE.BoxGeometry(blade.geometry.parameters.width,h,blade.geometry.parameters.depth);blade.position.y=e.opening+h/2;});
  for(let i=0;i<o.dots.length;i++){const dot=o.dots[i];dot.visible=Math.abs(e.flow)>.01&&running;const sign=e.flow>=0?1:-1;const f=((t*.15*sign+i/4)%1+1)%1;dot.position.copy(o.p).lerp(o.q,f);dot.position.y=e.type==='pipe'?Math.max(a.bed,b.bed)+e.width+.3:head(a)*(1-f)+head(b)*f+.15;const direction=o.q.clone().sub(o.p).setY(0).normalize().multiplyScalar(sign);dot.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),direction);}
 }
 // Screen length corresponding to 20 m at the camera target.
 const right=new THREE.Vector3().setFromMatrixColumn(camera.matrixWorld,0).multiplyScalar(20);const pa=controls.target.clone().project(camera),pb=controls.target.clone().add(right).project(camera);$('.scale-bar').style.width=`${Math.max(30,Math.abs(pb.x-pa.x)*host.clientWidth/2)}px`;
 $('.compass i').style.transform=`rotate(${-THREE.MathUtils.radToDeg(controls.getAzimuthalAngle())}deg)`;
}
function field(id,label,value,min,max,stepSize=.1,unit='ม.',disabled=running){return `<div class="field"><label for="${id}">${label}</label><div class="input-wrap"><input id="${id}" type="number" value="${value}" min="${min}" max="${max}" step="${stepSize}" ${disabled?'disabled':''}><span>${unit}</span></div></div>`;}
function renderInspector(){
 const panel=$('#selection-panel');const n=selected?.kind==='node'?findNode(selected.id):null;const e=selected?.kind==='edge'?findEdge(selected.id):null;function nearbyTerrain(node){const dx=node.width/2+8,dz=node.length/2+8;return (city.height(node.x-dx,node.z)+city.height(node.x+dx,node.z)+city.height(node.x,node.z-dz)+city.height(node.x,node.z+dz))/4;}
 if(n){
  const links=state.edges.filter(e=>e.a===n.id||e.b===n.id);
  panel.innerHTML=`<div class="selection-title"><h2>${esc(n.name)}</h2><span class="tiny-status">${n.spill>0?'น้ำล้น':''}</span></div><span class="selection-type">${TYPES[n.type]} · ${n.source?'จุดน้ำเข้า':n.sink?'จุดระบายออก':'แหล่งเก็บน้ำ'}</span><p class="terrain-reading">ระดับตลิ่ง <strong>${fmt(n.bed+n.bank)} ม.</strong> · พื้นดินรอบด้าน <strong>${fmt(nearbyTerrain(n))} ม.</strong></p><div class="water-level"><span>ระดับผิวน้ำ</span><div class="level-value"><span id="live-head">${fmt(head(n))}</span><small>เมตร</small></div></div><div class="level-meta"><span>ความลึกน้ำ<b><span id="live-depth">${fmt(n.volume/area(n))}</span> <small>ม.</small></b></span><span>ปริมาตรน้ำ<b><span id="live-volume">${fmt(n.volume,0)}</span> <small>ม³</small></b></span></div><div class="section-title">ขนาดและระดับ<span>หน่วยเมตร</span></div><div class="field-grid">${field('node-width','ความกว้าง',n.width,3,50)}${field('node-length','ความยาว',n.length,6,60)}${field('node-bed','ระดับท้องน้ำ',n.bed,-2,10)}${field('node-bank','ความสูงตลิ่ง',n.bank,.5,10)}${field('node-depth','ตั้งความลึกน้ำ',+(n.volume/area(n)).toFixed(2),0,n.bank)}${n.source?field('node-inflow','น้ำเข้าต่อวินาที',state.inputRate,0,30,.5,'ม³/วิ',false):''}${n.sink?field('outlet-rate','ระบายออก',state.outputRate,0,30,.5,'ม³/วิ',false):''}</div><small class="edit-note">${running?'หยุดจำลองเพื่อแก้ขนาดและระดับท้องน้ำ':'ปรับขนาดคงปริมาตรน้ำเดิม · ตั้งความลึกจะเปลี่ยนปริมาตร'}</small><div class="section-title">ทางเชื่อม<span>${links.length} เส้นทาง</span></div><div class="connections">${links.map(l=>{const other=findNode(l.a===n.id?l.b:l.a);return `<button class="connection-row" data-edge="${l.id}"><span>${l.gate?'⊞ ':l.type==='pipe'?'⊏ ':'⌁ '}${esc(other.name)}</span><strong data-live-flow="${l.id}">${fmt(Math.abs(l.flow),1)} ม³/วิ</strong></button>`}).join('')||'<p class="connection-empty">เลือกเครื่องมือเชื่อมคลองหรือท่อ แล้วเลือกแหล่งน้ำอีกจุด</p>'}</div><div class="section-title">ขอบเขตการไหล</div><div class="gate-presets"><button id="set-source" ${running?'disabled':''}>${n.source?'ยกเลิกน้ำเข้า':'ตั้งเป็นน้ำเข้า'}</button><button id="set-sink" ${running?'disabled':''}>${n.sink?'ยกเลิกน้ำออก':'ตั้งเป็นน้ำออก'}</button></div><button class="delete-btn" id="delete-selected" ${running?'disabled':''}>ลบ${TYPES[n.type]}นี้</button>`;
  for(const [id,key] of [['node-width','width'],['node-length','length'],['node-bed','bed'],['node-bank','bank']])$('#'+id).addEventListener('change',ev=>{const value=Number(ev.target.value);const candidate={...n,[key]:value};if(!ev.target.checkValidity()||!validateNode(candidate)||Math.abs(n.x)+candidate.width/2>99||Math.abs(n.z)+candidate.length/2>99){toast('ขนาดหรือระดับอยู่นอกขอบเขตที่กำหนด');renderInspector();return;}Object.assign(n,candidate);if(n.volume>area(n)*n.bank){toast('ปรับแล้วน้ำสูงกว่าตลิ่ง กดเริ่มเพื่อดูน้ำล้น');}geometryChanged();});
  $('#node-depth').onchange=ev=>{if(!ev.target.checkValidity()||!Number.isFinite(+ev.target.value)){renderInspector();return;}n.volume=area(n)*Number(ev.target.value);geometryChanged();};
  if(n.source)$('#node-inflow').onchange=ev=>{if(ev.target.checkValidity()&&Number.isFinite(+ev.target.value)){state.inputRate=+ev.target.value;syncInputs();}else renderInspector();};
  if(n.sink)$('#outlet-rate').onchange=ev=>{if(ev.target.checkValidity()&&Number.isFinite(+ev.target.value))state.outputRate=+ev.target.value;else renderInspector();};
  $('#set-source').onclick=()=>{const enable=!n.source;state.nodes.forEach(o=>o.source=false);n.source=enable;if(enable)n.sink=false;geometryChanged();};
  $('#set-sink').onclick=()=>{const enable=!n.sink;state.nodes.forEach(o=>o.sink=false);n.sink=enable;if(enable)n.source=false;geometryChanged();};
 }else if(e){
  const a=findNode(e.a),b=findNode(e.b);panel.innerHTML=`<div class="selection-title"><h2>${e.dam?'เขื่อนกักเก็บน้ำ':e.gate?'ประตูระบายน้ำ':e.type==='pipe'?'ท่อเชื่อม':'คลองเชื่อม'}</h2></div><span class="selection-type">${esc(a.name)} · ${esc(b.name)}</span><div class="water-level"><span>อัตราการไหล</span><div class="level-value"><span id="live-edge-flow">${fmt(Math.abs(e.flow))}</span><small>ม³/วิ</small></div></div><p class="flow-direction" id="flow-direction">${flowText(e)}</p>${e.dam?field('dam-crest','ระดับสันเขื่อน',e.crest??Math.max(a.bed,b.bed)+3,-2,20,.1,'ม.')+'<small class="edit-note">น้ำระบายข้ามสันเมื่อระดับน้ำสูงกว่าค่าที่ตั้ง</small>':''}${e.gate?`<div class="gate-control"><div class="label-row"><label for="gate-opening">${e.dam?'ช่องเปิดเขื่อน':'ช่องเปิดประตู'}</label><strong><span id="opening-value">${fmt(e.opening)}</span> ม.</strong></div><input id="gate-opening" type="range" min="0" max="${openingLimit(e)}" step=".05" value="${e.opening}"><div class="range-labels"><span>ปิดสนิท</span><span>${fmt(openingLimit(e),1)} ม.</span></div><div class="gate-presets"><button id="close-gate">ปิด</button><button id="open-gate">เปิดสุด</button></div></div>`:''}<div class="section-title">ขนาดทางเชื่อม</div><div class="field-grid">${field('edge-width',e.type==='pipe'?'เส้นผ่านศูนย์กลาง':'ความกว้าง',e.width,e.type==='pipe'?.3:1,e.type==='pipe'?5:15)}<div class="field"><label>ระยะระหว่างจุด</label><div class="input-wrap"><input disabled value="${fmt(Math.hypot(a.x-b.x,a.z-b.z),1)}"><span>ม.</span></div></div></div><div class="level-meta"><span>${esc(a.name)}<b><span id="edge-ha">${fmt(head(a))}</span> <small>ม.</small></b></span><span>${esc(b.name)}<b><span id="edge-hb">${fmt(head(b))}</span> <small>ม.</small></b></span></div><small class="edit-note">น้ำไหลจากระดับสูงไปต่ำ · ${e.type==='pipe'?'ท่อใช้การประมาณการสูญเสียพลังงาน':e.dam?'ช่องเขื่อนระบายผ่านประตูและสันทางน้ำล้น':'คลองใช้ความลาดระดับน้ำและความต้านทาน'}</small><div class="gate-presets"><button id="toggle-gate" ${running?'disabled':''}>${e.gate?'ถอดประตู':'ติดตั้งประตู'}</button></div><button class="delete-btn" id="delete-selected" ${running?'disabled':''}>ลบทางเชื่อมนี้</button>`;
  if(e.dam)$('#dam-crest').onchange=ev=>{if(!ev.target.checkValidity()||!Number.isFinite(+ev.target.value)){renderInspector();return;}const base=Math.max(a.bed,b.bed);if(+ev.target.value<base+.25){toast('สันเขื่อนต้องสูงกว่าท้องคลองอย่างน้อย 0.25 ม.');renderInspector();return;}e.crest=+ev.target.value;e.opening=Math.min(e.opening,Math.max(.2,e.crest-base));geometryChanged();};
  if(e.gate){$('#gate-opening').oninput=ev=>setOpening(e,+ev.target.value);$('#close-gate').onclick=()=>setOpening(e,0);$('#open-gate').onclick=()=>setOpening(e,openingLimit(e));}
  $('#edge-width').onchange=ev=>{if(!ev.target.checkValidity()||!Number.isFinite(+ev.target.value)){renderInspector();return;}e.width=+ev.target.value;if(e.type==='pipe')e.opening=Math.min(e.opening,e.width);geometryChanged();};
  $('#toggle-gate').textContent=e.dam?(e.gate?'ถอดบานประตูเขื่อน':'ติดตั้งบานประตูเขื่อน'):(e.gate?'ถอดประตู':'ติดตั้งประตู');$('#toggle-gate').onclick=()=>{e.gate=!e.gate;geometryChanged();};
 }else panel.innerHTML='<div class="empty-panel"><h2>เริ่มสำรวจทางน้ำ</h2><p>เลือกชิ้นส่วนบนแผนที่เพื่อดูระดับน้ำ หรือวางแหล่งน้ำใหม่จากแถบด้านซ้าย</p></div>';
 $$('.connection-row').forEach(btn=>btn.onclick=()=>select({kind:'edge',id:btn.dataset.edge}));if($('#delete-selected'))$('#delete-selected').onclick=deleteSelected;
 updateLive();
}
function flowText(e){if(!running)return 'เริ่มจำลองเพื่อดูทิศทางและอัตราการไหล';if(Math.abs(e.flow)<.001)return e.gate&&e.opening===0?'ประตูปิดสนิท · ไม่มีน้ำไหลผ่าน':'ไม่มีการไหลในขณะนี้';return `${esc(findNode(e.flow>0?e.a:e.b).name)} → ${esc(findNode(e.flow>0?e.b:e.a).name)}`;}
function setOpening(e,v){if(!e.gate||!Number.isFinite(v)||v<0||v>openingLimit(e))throw Error('ช่องเปิดอยู่นอกขอบเขต');e.opening=v;if(selected?.id===e.id){$('#opening-value')&&($('#opening-value').textContent=fmt(v));$('#gate-opening')&&($('#gate-opening').value=v);}if(!running&&state.time===0)snapshot=structuredClone(state);updateVisuals(state.time);}
function updateLive(){
 $('#total-water').textContent=fmt(total(state),0);$('#total-in').textContent=fmt(state.inflow,0);$('#total-out').textContent=fmt(state.outflow,0);$('#total-overflow').textContent=fmt(state.overflow,1);$('#total-overflow').classList.toggle('warning',state.overflow>.01);$('#balance-note').textContent=Math.abs(balance(state))<.001?'ปริมาณน้ำสมดุล':'กำลังตรวจสอบสมดุลน้ำ';
 const sec=Math.floor(state.time);$('#sim-time').textContent=`${Math.floor(sec/60).toString().padStart(2,'0')}:${(sec%60).toString().padStart(2,'0')}`;
 if(selected?.kind==='node'){const n=findNode(selected.id);if(n&&$('#live-head')){$('#live-head').textContent=fmt(head(n));$('#live-depth').textContent=fmt(n.volume/area(n));$('#live-volume').textContent=fmt(n.volume,0);$('.tiny-status').textContent=n.spill>0?'น้ำล้น':'';}}
 if(selected?.kind==='edge'){const e=findEdge(selected.id);if(e&&$('#live-edge-flow')){$('#live-edge-flow').textContent=fmt(Math.abs(e.flow));$('#flow-direction').innerHTML=flowText(e);$('#edge-ha').textContent=fmt(head(findNode(e.a)));$('#edge-hb').textContent=fmt(head(findNode(e.b)));}}
 $$('[data-live-flow]').forEach(el=>{const e=findEdge(el.dataset.liveFlow);if(e)el.textContent=fmt(Math.abs(e.flow),1)+' ม³/วิ';});
}
function toast(message){clearTimeout(toastTimer);$('#toast').textContent=message;$('#toast').classList.add('show');toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3000);}
function select(s){selected=s;renderInspector();updateVisuals(state.time);}
function geometryChanged(){rebase(state);snapshot=structuredClone(state);rebuild();}
function requirePaused(){if(running){toast('หยุดจำลองก่อนแก้โครงสร้างทางน้ำ');return false;}return true;}
function deleteSelected(){if(!requirePaused()||!selected)return;if(selected.kind==='node'){state.nodes=state.nodes.filter(n=>n.id!==selected.id);state.edges=state.edges.filter(e=>e.a!==selected.id&&e.b!==selected.id);}else state.edges=state.edges.filter(e=>e.id!==selected.id);selected=null;geometryChanged();toast('ลบชิ้นส่วนแล้ว');}
function setMode(value){mode=value;connectionStart=null;$$('[data-tool]').forEach(b=>b.classList.toggle('active',b.dataset.tool===mode));$('#orbit-btn').classList.toggle('on',mode==='orbit');controls.mouseButtons.LEFT=mode==='orbit'?THREE.MOUSE.ROTATE:null;controls.touches.ONE=mode==='orbit'?THREE.TOUCH.ROTATE:null;$('#mode-hint').textContent=({select:'เลือกชิ้นส่วนเพื่อดูระดับน้ำ · ลากเพื่อย้าย',orbit:'ลากเพื่อหมุนกล้อง · ล้อเมาส์หรือสองนิ้วเพื่อซูม',river:'คลิกแผนที่เพื่อวางแม่น้ำ',canal:'คลิกแผนที่เพื่อวางคลอง',pond:'คลิกแผนที่เพื่อวางบึง',channel:'เลือกแหล่งน้ำต้นทาง แล้วเลือกปลายทาง',pipe:'เลือกแหล่งน้ำ 2 จุดเพื่อเชื่อมท่อ',gate:'คลิกทางเชื่อมเพื่อติดตั้งประตูระบายน้ำ',dam:'คลิกคลองเพื่อสร้างเขื่อนกักเก็บน้ำ'})[mode];renderer.domElement.style.cursor=mode==='orbit'?'grab':mode==='select'?'default':'crosshair';}
function pointerAt(ev){camera.updateMatrixWorld(true);const rect=renderer.domElement.getBoundingClientRect();pointer.set((ev.clientX-rect.left)/rect.width*2-1,-(ev.clientY-rect.top)/rect.height*2+1);raycaster.setFromCamera(pointer,camera);}
function pick(ev){pointerAt(ev);const hits=raycaster.intersectObjects(pickables,false);return hits[0]?.object.userData||null;}
function ground(ev){pointerAt(ev);const hit=city?raycaster.intersectObject(city.terrain,false)[0]:null;return hit?hit.point:raycaster.ray.intersectPlane(plane,new THREE.Vector3());}
function addNode(type,p){if(!requirePaused())return;if(!p||Math.abs(p.x)>95||Math.abs(p.z)>95){toast('วางชิ้นส่วนภายในขอบแผนที่');return;}if(state.nodes.length>=35){toast('พื้นที่ทดลองรองรับแหล่งน้ำสูงสุด 35 จุด');return;}
 const sizes={river:[18,32],canal:[10,24],pond:[30,32]};const [width,length]=sizes[type];const x=Math.max(-99+width/2,Math.min(99-width/2,Math.round(p.x/2)*2)),z=Math.max(-99+length/2,Math.min(99-length/2,Math.round(p.z/2)*2));
 if(state.nodes.some(n=>Math.abs(n.x-x)<(n.width+width)/2+1&&Math.abs(n.z-z)<(n.length+length)/2+1)){toast('ตำแหน่งนี้ทับกับแหล่งน้ำเดิม ลองเว้นระยะอีกนิด');return;}
 const id='n'+nextId++;state.nodes.push({id,type,name:TYPES[type]+' '+nextId,x,z,width,length,bed:Math.max(-2,Math.round((city.height(x,z)-3)*10)/10),bank:3,volume:0,spill:0,source:state.nodes.length===0,sink:false});selected={kind:'node',id};geometryChanged();toast('วาง'+TYPES[type]+'แล้ว · ตั้งความลึกในแผงด้านขวา');setMode('select');
}
function addConnection(aid,bid,type){if(!requirePaused())return null;if(aid===bid){toast('เลือกแหล่งน้ำอีกจุด');return null;}if(state.edges.some(e=>(e.a===aid&&e.b===bid)||(e.a===bid&&e.b===aid))){toast('สองจุดนี้มีทางเชื่อมแล้ว');return null;}const a=findNode(aid),b=findNode(bid);if(!a||!b)throw Error('ไม่พบแหล่งน้ำ');const p=endPoint(a,b),q=endPoint(b,a);if(Math.hypot(a.x-b.x,a.z-b.z)<Math.hypot(p.x-a.x,p.z-a.z)+Math.hypot(q.x-b.x,q.z-b.z)+2){toast('เว้นช่องว่างระหว่างแหล่งน้ำอย่างน้อย 2 เมตร');return null;}const e={id:'e'+nextId++,a:aid,b:bid,type,width:type==='pipe'?1:4,opening:1,gate:false,flow:0};state.edges.push(e);selected={kind:'edge',id:e.id};geometryChanged();setMode('select');toast('เชื่อมทางน้ำแล้ว');return e;}
function placeGate(hit){if(!requirePaused())return;if(hit?.kind!=='edge'){toast('วางสิ่งก่อสร้างบนทางเชื่อมคลองระหว่างแหล่งน้ำ');return;}const installDam=mode==='dam';const e=findEdge(hit.id);if(installDam){ if(e.type==='pipe'){toast('เขื่อนวางได้บนคลอง เลือกคลองที่เชื่อมระหว่างแหล่งน้ำ');return;}const a=findNode(e.a),b=findNode(e.b);e.dam=true;e.gate=true;e.crest=Math.max(a.bed,b.bed)+3;e.opening=Math.min(1.1,e.crest-Math.max(a.bed,b.bed));}else e.gate=true;selected=hit;geometryChanged();setMode('select');toast(installDam?'สร้างเขื่อนแล้ว · ปรับระดับสันและประตูทางน้ำด้านขวา':'ติดตั้งประตูแล้ว ปรับช่องเปิดได้ด้านขวา');}
function activatePoint(ev){if(mode==='orbit')return;const hit=pick(ev);
 if(['river','canal','pond'].includes(mode)){addNode(mode,ground(ev));return;}
 if(mode==='gate'){placeGate(hit);return;}
 if(mode==='channel'||mode==='pipe'){if(!requirePaused())return;if(hit?.kind!=='node'){toast('เลือกที่แหล่งน้ำ ไม่ใช่ทางเชื่อม');return;}if(!connectionStart){connectionStart=hit.id;select(hit);$('#mode-hint').textContent='ต้นทาง: '+findNode(hit.id).name+' · เลือกแหล่งน้ำปลายทาง';}else{const e=addConnection(connectionStart,hit.id,mode);if(e)connectionStart=null;}return;}
 select(hit);}
let pointerDown=null,dragged=false,dragNode=null,originalPosition=null;
renderer.domElement.addEventListener('pointerdown',ev=>{if(ev.button!==0||mode==='orbit')return;pointerDown={x:ev.clientX,y:ev.clientY};dragged=false;const hit=pick(ev);if(mode==='select'&&hit?.kind==='node'&&!running){dragNode=findNode(hit.id);originalPosition={x:dragNode.x,z:dragNode.z};select(hit);renderer.domElement.setPointerCapture(ev.pointerId);}});
renderer.domElement.addEventListener('pointermove',ev=>{if(!pointerDown||!dragNode)return;if(Math.hypot(ev.clientX-pointerDown.x,ev.clientY-pointerDown.y)<5&&!dragged)return;dragged=true;const p=ground(ev);if(!p)return;const n=dragNode;n.x=Math.max(-99+n.width/2,Math.min(99-n.width/2,Math.round(p.x/2)*2));n.z=Math.max(-99+n.length/2,Math.min(99-n.length/2,Math.round(p.z/2)*2));rebuild({refreshCity:false});});
renderer.domElement.addEventListener('pointerup',ev=>{if(ev.button!==0)return;if(dragged&&dragNode){const n=dragNode;if(state.nodes.some(o=>o.id!==n.id&&Math.abs(o.x-n.x)<(o.width+n.width)/2+1&&Math.abs(o.z-n.z)<(o.length+n.length)/2+1)){Object.assign(n,originalPosition);toast('ชิ้นส่วนซ้อนกัน คืนตำแหน่งเดิมแล้ว');}geometryChanged();}else if(pointerDown)activatePoint(ev);pointerDown=null;dragNode=null;dragged=false;});
renderer.domElement.addEventListener('pointercancel',()=>{if(dragNode&&originalPosition){Object.assign(dragNode,originalPosition);rebuild();}pointerDown=null;dragNode=null;dragged=false;});
renderer.domElement.addEventListener('contextmenu',ev=>ev.preventDefault());
$$('[data-tool]').forEach(btn=>{btn.onclick=()=>setMode(btn.dataset.tool);btn.ondragstart=ev=>{ev.dataTransfer.setData('text/plain',btn.dataset.tool);ev.dataTransfer.effectAllowed='copy';};});
viewport.addEventListener('dragover',ev=>{ev.preventDefault();ev.dataTransfer.dropEffect='copy';});viewport.addEventListener('drop',ev=>{ev.preventDefault();const type=ev.dataTransfer.getData('text/plain');if(['river','canal','pond'].includes(type))addNode(type,ground(ev));if(type==='gate'||type==='dam'){setMode(type);placeGate(pick(ev));}});
function setRunning(value){if(value&&state.nodes.length===0){toast('วางแหล่งน้ำก่อนเริ่มจำลอง');return;}if(value&&!running&&state.time===0)snapshot=structuredClone(state);running=value;accumulator=0;$('#play-btn').innerHTML=running?'<span class="play-glyph" aria-hidden="true"></span> หยุดชั่วคราว':'<span class="play-glyph" aria-hidden="true"></span> เริ่มจำลอง';$('#play-btn').classList.toggle('running',running);$('#state-badge').textContent=running?'กำลังจำลอง':'หยุดชั่วคราว';$('#state-badge').classList.toggle('running',running);renderInspector();}
$('#play-btn').onclick=()=>setRunning(!running);$('#speed').onchange=ev=>speed=+ev.target.value;$('#reset-btn').onclick=()=>{setRunning(false);state=structuredClone(snapshot);syncInputs();rebuild();toast('คืนค่าก่อนเริ่มจำลองแล้ว');};
$('#inflow').oninput=ev=>{state.inputRate=+ev.target.value;$('#inflow-value').textContent=fmt(state.inputRate,1);if($('#node-inflow'))$('#node-inflow').value=state.inputRate;};
function syncInputs(){$('#inflow').value=state.inputRate;$('#inflow-value').textContent=fmt(state.inputRate,1);}
let confirmAction=null;function confirmActionDialog(title,text,action){$('#confirm-title').textContent=title;$('#confirm-text').textContent=text;confirmAction=action;$('#confirm-dialog').showModal();}
$('#confirm-cancel').onclick=()=>$('#confirm-dialog').close();$('#confirm-ok').onclick=()=>{$('#confirm-dialog').close();confirmAction?.();};
$('#example-btn').onclick=()=>confirmActionDialog('โหลดฉากตัวอย่าง?','การจัดวางและผลทดลองปัจจุบันจะถูกแทนที่ด้วยฉากเริ่มต้น',()=>{setRunning(false);state=example();snapshot=structuredClone(state);selected={kind:'node',id:'n3'};setMode('select');syncInputs();rebuild();});
$('#clear-btn').onclick=()=>confirmActionDialog('เริ่มพื้นที่ว่าง?','ลบแหล่งน้ำและทางเชื่อมทั้งหมด เพื่อเริ่มออกแบบใหม่',()=>{setRunning(false);state={nodes:[],edges:[],time:0,inputRate:4,outputRate:3,inflow:0,outflow:0,overflow:0,initial:0};snapshot=structuredClone(state);selected=null;setMode('river');syncInputs();rebuild();});
$('#help-btn').onclick=()=>$('#help-dialog').showModal();$('#orbit-btn').onclick=()=>setMode(mode==='orbit'?'select':'orbit');$('#top-btn').onclick=()=>{camera.position.set(0,290,.1);controls.target.set(0,0,0);controls.update();updateVisuals(state.time);};$('#home-btn').onclick=()=>fitCamera();$('#grid-btn').onclick=()=>{showGrid=!showGrid;city.grid.visible=showGrid;$('#grid-btn').classList.toggle('on',showGrid);$('#grid-btn').setAttribute('aria-pressed',String(showGrid));};
$('#city-btn').onclick=()=>{showCity=!showCity;city.urban.visible=showCity;$('#city-btn').classList.toggle('on',showCity);$('#city-btn').setAttribute('aria-pressed',String(showCity));};
$('#labels-btn').onclick=()=>{showLabels=!showLabels;$('#labels-btn').classList.toggle('on',showLabels);$('#labels-btn').setAttribute('aria-pressed',String(showLabels));updateVisuals(state.time);};
document.addEventListener('keydown',ev=>{if(['INPUT','SELECT','TEXTAREA'].includes(document.activeElement?.tagName)||$('dialog[open]'))return;if(ev.key==='Escape')setMode('select');if(ev.key==='1')setMode('select');if(ev.key==='Delete'||ev.key==='Backspace'){ev.preventDefault();deleteSelected();}if(ev.code==='Space'){ev.preventDefault();setRunning(!running);}});
function fitCamera(){const distance=370/Math.min(1,host.clientWidth/host.clientHeight);camera.position.set(180,175,235).normalize().multiplyScalar(distance);controls.target.set(0,0,0);controls.update();updateVisuals(state.time);}
function resize(){const w=host.clientWidth,h=host.clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();}new ResizeObserver(resize).observe(host);resize();fitCamera();rebuild();setMode('select');
let previous=performance.now(),lastUi=0;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
function frame(now){requestAnimationFrame(frame);const elapsed=Math.min(.1,(now-previous)/1000);previous=now;controls.update();if(running){accumulator+=elapsed*speed;let count=0;while(accumulator>=.05&&count<50){step(state,.05);accumulator-=.05;count++;}}clockUniform.value=reduced?0:now/1800;updateVisuals(reduced?0:state.time);if(now-lastUi>120){updateLive();lastUi=now;}renderer.render(scene,camera);}requestAnimationFrame(frame);
// Browser agents use the same actions and state as the visible workspace.
const context=document.modelContext;if(context?.registerTool){
 const lifecycle=new AbortController();const tools=[
 {name:'read_water_system',title:'อ่านสถานะระบบน้ำ',description:'Read water levels, dimensions, flows, gate settings and mass balance in the current sandbox.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute(input){if(!input||Object.keys(input).length)throw Error('Expected empty object');return {running,time:state.time,nodes:state.nodes.map(n=>({...n,head:head(n),depth:n.volume/area(n)})),edges:structuredClone(state.edges),volume:total(state),inflow:state.inflow,outflow:state.outflow,overflow:state.overflow,balanceError:balance(state)};}},
 {name:'set_water_gate_opening',title:'ปรับช่องเปิดประตู',description:'Set an existing gate opening in meters and select it in the inspector.',inputSchema:{type:'object',properties:{edgeId:{type:'string'},openingMeters:{type:'number',minimum:0,maximum:4}},required:['edgeId','openingMeters'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||Object.keys(input).some(k=>!['edgeId','openingMeters'].includes(k))||typeof input.edgeId!=='string'||typeof input.openingMeters!=='number')throw Error('Invalid input');const e=findEdge(input.edgeId);if(!e?.gate)throw Error('Gate not found');const max=e.type==='pipe'?e.width:4;if(!Number.isFinite(input.openingMeters)||input.openingMeters<0||input.openingMeters>max)throw Error('Opening outside range');select({kind:'edge',id:e.id});setOpening(e,input.openingMeters);return {edgeId:e.id,openingMeters:e.opening};}},
 {name:'set_water_simulation_running',title:'เริ่มหรือหยุดจำลองน้ำ',description:'Start or pause the existing water simulation.',inputSchema:{type:'object',properties:{running:{type:'boolean'}},required:['running'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||typeof input.running!=='boolean'||Object.keys(input).length!==1)throw Error('Expected running boolean');if(input.running&&!state.nodes.length)throw Error('Add water nodes first');setRunning(input.running);return {running};}}
 ];for(const tool of tools){try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}}
 window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});
}
